In [12]:
        
with open("./btnEvent.py" , "r") as f:
    d = f.read()

for i in range(4 , 37,3):
    x = f'''                        self.ui.cmraBt_%02d,self.ui.cmraBt_%02d,self.ui.cmraBt_%02d,\n'''%(i,i+1,i+2)
    d+=x
with open("./btnEvent2.py" , "w") as f:
    f.write(d)

In [7]:
import numpy as np

In [8]:
np.zeros((10,10,10,10))

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [12]:
with open("./btnEvent.py" , "r") as f:
    x = f.read()
with open("./btnEvent_backup.py" , "w") as f:
    f.write(x)

for idx in range(3, 33):
    d = f'''    def fullscreen{idx:02d}(self):
            cam  =self.currentCam = 'cam{idx:02d}'
            camera = self.cameras[cam]
            self.loadCameraSet()
            self.setLayerCorlr()
            now = time.time()
            if now - self.dclickTime[1]  < 0.3:
                self.resizeCamers(cam ,camera )
            self.dclickTime[1] = time.time()


'''
    x+=d
with open("./btnEvent.py" , "w") as f:
    f.write(x)


In [19]:
tmp = 'self.cameras = {'
for i in range(1, 33):
    tmp += f'"cam{i:02d}" : self.ui.cmraBt_{i:02d}, '
    if i%4 == 3:
        tmp+="\n"
print(tmp)

self.cameras = {"cam01" : self.ui.cmraBt_01, "cam02" : self.ui.cmraBt_02, "cam03" : self.ui.cmraBt_03, 
"cam04" : self.ui.cmraBt_04, "cam05" : self.ui.cmraBt_05, "cam06" : self.ui.cmraBt_06, "cam07" : self.ui.cmraBt_07, 
"cam08" : self.ui.cmraBt_08, "cam09" : self.ui.cmraBt_09, "cam10" : self.ui.cmraBt_10, "cam11" : self.ui.cmraBt_11, 
"cam12" : self.ui.cmraBt_12, "cam13" : self.ui.cmraBt_13, "cam14" : self.ui.cmraBt_14, "cam15" : self.ui.cmraBt_15, 
"cam16" : self.ui.cmraBt_16, "cam17" : self.ui.cmraBt_17, "cam18" : self.ui.cmraBt_18, "cam19" : self.ui.cmraBt_19, 
"cam20" : self.ui.cmraBt_20, "cam21" : self.ui.cmraBt_21, "cam22" : self.ui.cmraBt_22, "cam23" : self.ui.cmraBt_23, 
"cam24" : self.ui.cmraBt_24, "cam25" : self.ui.cmraBt_25, "cam26" : self.ui.cmraBt_26, "cam27" : self.ui.cmraBt_27, 
"cam28" : self.ui.cmraBt_28, "cam29" : self.ui.cmraBt_29, "cam30" : self.ui.cmraBt_30, "cam31" : self.ui.cmraBt_31, 
"cam32" : self.ui.cmraBt_32, 


In [20]:
import cv2

In [29]:
video = cv2.VideoCapture("http://195.196.36.242/mjpg/video.mjpg")

In [32]:
ret, frame = video.read()
print(frame)

[[[  0   0   0]
  [  4   4   4]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  1   1   1]
  [ 15  15  15]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 16  16  16]
  [  0   0   0]
  [  3   3   3]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 79 104 102]
  [ 80 105 103]
  [ 84 104 103]
  ...
  [ 61  61  61]
  [ 67  67  67]
  [ 61  61  61]]

 [[ 84 104 103]
  [ 84 104 103]
  [ 86 104 103]
  ...
  [ 62  58  59]
  [ 69  65  66]
  [ 63  59  60]]

 [[ 84 104 103]
  [ 85 105 104]
  [ 87 105 104]
  ...
  [ 62  58  59]
  [ 64  60  61]
  [ 55  51  52]]]


In [33]:
for i in range(30):
    ret, frame = video.read()
    cv2.imshow("" , frame)
    cv2.waitKey(1)

KeyboardInterrupt: 

In [1]:
from multiprocessing import Queue
q = Queue()
print(dir(q))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_after_fork', '_buffer', '_close', '_closed', '_feed', '_finalize_close', '_finalize_join', '_ignore_epipe', '_joincancelled', '_jointhread', '_maxsize', '_notempty', '_opid', '_poll', '_reader', '_recv_bytes', '_rlock', '_sem', '_send_bytes', '_start_thread', '_thread', '_wlock', '_writer', 'cancel_join_thread', 'close', 'empty', 'full', 'get', 'get_nowait', 'join_thread', 'put', 'put_nowait', 'qsize']


In [1]:
240*6

1440

In [10]:
1440/3

480.0

In [3]:
140*6

840

In [11]:
840/3

280.0