In [12]:
        
with open("./btnEvent.py" , "r") as f:
    d = f.read()

for i in range(4 , 37,3):
    x = f'''                        self.ui.cmraBt_%02d,self.ui.cmraBt_%02d,self.ui.cmraBt_%02d,\n'''%(i,i+1,i+2)
    d+=x
with open("./btnEvent2.py" , "w") as f:
    f.write(d)

In [7]:
import numpy as np

In [8]:
np.zeros((10,10,10,10))

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [9]:
with open("./btnEvent.py" , "r") as f:
    x = f.read()
with open("./btnEvent_backup.py" , "w") as f:
    f.write(x)

import re

xs = re.findall('self\.ui\.cmraBt\_[0-9]+ \= DragBtn\(self\.ui\.dragCamBase\)',x)
for xx in xs:
    print(xx)
    num = xx.split('self.ui.cmraBt_')[1].split(" =")[0]
    x = x.replace(f'self.ui.cmraBt_{num} = DragBtn(self.ui.dragCamBase)' , 
    f'self.ui.cmraBt_{num} = DragBtn(self.ui.dragCamBase)\n        self.ui.cmraBt_{num}.func = self.showSetting{num}')

with open("./btnEvent2.py" , "w") as f:
    f.write(x)

self.ui.cmraBt_02 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_03 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_04 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_05 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_06 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_07 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_08 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_09 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_10 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_11 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_12 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_13 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_14 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_15 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_16 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_17 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_18 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_19 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_20 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_21 = DragBtn(self.ui.dragCamBase)
self.ui.cmraBt_22 = 

In [19]:
tmp = 'self.cameras = {'
for i in range(1, 33):
    tmp += f'"cam{i:02d}" : self.ui.cmraBt_{i:02d}, '
    if i%4 == 3:
        tmp+="\n"
print(tmp)

self.cameras = {"cam01" : self.ui.cmraBt_01, "cam02" : self.ui.cmraBt_02, "cam03" : self.ui.cmraBt_03, 
"cam04" : self.ui.cmraBt_04, "cam05" : self.ui.cmraBt_05, "cam06" : self.ui.cmraBt_06, "cam07" : self.ui.cmraBt_07, 
"cam08" : self.ui.cmraBt_08, "cam09" : self.ui.cmraBt_09, "cam10" : self.ui.cmraBt_10, "cam11" : self.ui.cmraBt_11, 
"cam12" : self.ui.cmraBt_12, "cam13" : self.ui.cmraBt_13, "cam14" : self.ui.cmraBt_14, "cam15" : self.ui.cmraBt_15, 
"cam16" : self.ui.cmraBt_16, "cam17" : self.ui.cmraBt_17, "cam18" : self.ui.cmraBt_18, "cam19" : self.ui.cmraBt_19, 
"cam20" : self.ui.cmraBt_20, "cam21" : self.ui.cmraBt_21, "cam22" : self.ui.cmraBt_22, "cam23" : self.ui.cmraBt_23, 
"cam24" : self.ui.cmraBt_24, "cam25" : self.ui.cmraBt_25, "cam26" : self.ui.cmraBt_26, "cam27" : self.ui.cmraBt_27, 
"cam28" : self.ui.cmraBt_28, "cam29" : self.ui.cmraBt_29, "cam30" : self.ui.cmraBt_30, "cam31" : self.ui.cmraBt_31, 
"cam32" : self.ui.cmraBt_32, 


In [20]:
import cv2

In [29]:
video = cv2.VideoCapture("http://195.196.36.242/mjpg/video.mjpg")

In [32]:
ret, frame = video.read()
print(frame)

[[[  0   0   0]
  [  4   4   4]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  1   1   1]
  [ 15  15  15]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 16  16  16]
  [  0   0   0]
  [  3   3   3]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 79 104 102]
  [ 80 105 103]
  [ 84 104 103]
  ...
  [ 61  61  61]
  [ 67  67  67]
  [ 61  61  61]]

 [[ 84 104 103]
  [ 84 104 103]
  [ 86 104 103]
  ...
  [ 62  58  59]
  [ 69  65  66]
  [ 63  59  60]]

 [[ 84 104 103]
  [ 85 105 104]
  [ 87 105 104]
  ...
  [ 62  58  59]
  [ 64  60  61]
  [ 55  51  52]]]


In [33]:
for i in range(30):
    ret, frame = video.read()
    cv2.imshow("" , frame)
    cv2.waitKey(1)

KeyboardInterrupt: 

In [1]:
from multiprocessing import Queue
q = Queue()
print(dir(q))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_after_fork', '_buffer', '_close', '_closed', '_feed', '_finalize_close', '_finalize_join', '_ignore_epipe', '_joincancelled', '_jointhread', '_maxsize', '_notempty', '_opid', '_poll', '_reader', '_recv_bytes', '_rlock', '_sem', '_send_bytes', '_start_thread', '_thread', '_wlock', '_writer', 'cancel_join_thread', 'close', 'empty', 'full', 'get', 'get_nowait', 'join_thread', 'put', 'put_nowait', 'qsize']


In [1]:
240*6

1440

In [10]:
1440/3

480.0

In [3]:
140*6

840

In [11]:
840/3

280.0

In [16]:
"Abc".endswith("bsc")

False

In [2]:
with open("./btnEvent.py" , "r" , encoding="utf8") as f:
    d = f.read()

In [10]:
a = d.split('#showSetting17')[0]
b = d.split('#showSetting17')[1]



In [11]:
for i in range(2 , 33):
    code = f'''    def showSetting01(self):
        now = time.time()
        if self.settingLayer.isHidden():
            self.settingLayer.show()
            self.settingLayer.resize(259 , 831)
            self.settingLayer.move(500-76 , 80-10)
            self.settingLayer.setStyleSheet('background-color: rgba(0, 52, 63, 255);')
        else:
            self.settingLayer.hide()
            self.loadCameraSet(base = True)
            self.settingLayer.resize(259 , 831)
            self.settingLayer.move(1567 , 80)
            self.settingLayer.setStyleSheet(u"background-color: rgba(50, 50, 80, 50);")'''
    a+=code



In [21]:
x = [f'        self.ui.cmraBt_{i:02d} = DragBtn(self.ui.widget_2)\n        self.ui.cmraBt_{i:02d}.resize(51,30)\n        self.ui.cmraBt_{i:02d}.move(int(20+50*{(i-1)%6}), int(60 + 40*{(i-1)//6}) )\n        self.ui.cmraBt_{i:02d}.setIcon(QPixmap(u"datas/images/bt1.png"))\n        self.ui.cmraBt_{i:02d}.setIconSize(QSize(28,28))\n        self.ui.cmraBt_{i:02d}.setText("{i:02d}")\n        self.ui.cmraBt_{i:02d}.setStyleSheet("color: rgb(255, 255, 255);")' for i in range(1 , 33)]

In [22]:
d2 = a + "\n".join(x) + b

In [12]:
with open("./btnEvent2.py" , "w") as f:
    f.write(a+b)

In [24]:
a = '''self.cameras = {"cam01" : self.ui.camVideo_01, "cam02" : self.ui.camVideo_02, "cam03" : self.ui.camVideo_03, 
                        "cam04" : self.ui.camVideo_04, "cam05" : self.ui.camVideo_05, "cam06" : self.ui.camVideo_06, "cam07" : self.ui.camVideo_07, 
                        "cam08" : self.ui.camVideo_08, "cam09" : self.ui.camVideo_09, "cam10" : self.ui.camVideo_10, "cam11" : self.ui.camVideo_11, 
                        "cam12" : self.ui.camVideo_12, "cam13" : self.ui.camVideo_13, "cam14" : self.ui.camVideo_14, "cam15" : self.ui.camVideo_15, 
                        "cam16" : self.ui.camVideo_16, "cam17" : self.ui.camVideo_17, "cam18" : self.ui.camVideo_18, "cam19" : self.ui.camVideo_19, 
                        "cam20" : self.ui.camVideo_20, "cam21" : self.ui.camVideo_21, "cam22" : self.ui.camVideo_22, "cam23" : self.ui.camVideo_23, 
                        "cam24" : self.ui.camVideo_24, "cam25" : self.ui.camVideo_25, "cam26" : self.ui.camVideo_26, "cam27" : self.ui.camVideo_27, 
                        "cam28" : self.ui.camVideo_28, "cam29" : self.ui.camVideo_29, "cam30" : self.ui.camVideo_30, "cam31" : self.ui.camVideo_31, 
                        "cam32" : self.ui.camVideo_32}'''

In [25]:
a = a.replace('camVideo_' , 'widget_2')

In [27]:
print(a)


self.cameras = {"cam01" : self.ui.widget_201, "cam02" : self.ui.widget_202, "cam03" : self.ui.widget_203, 
                        "cam04" : self.ui.widget_204, "cam05" : self.ui.widget_205, "cam06" : self.ui.widget_206, "cam07" : self.ui.widget_207, 
                        "cam08" : self.ui.widget_208, "cam09" : self.ui.widget_209, "cam10" : self.ui.widget_210, "cam11" : self.ui.widget_211, 
                        "cam12" : self.ui.widget_212, "cam13" : self.ui.widget_213, "cam14" : self.ui.widget_214, "cam15" : self.ui.widget_215, 
                        "cam16" : self.ui.widget_216, "cam17" : self.ui.widget_217, "cam18" : self.ui.widget_218, "cam19" : self.ui.widget_219, 
                        "cam20" : self.ui.widget_220, "cam21" : self.ui.widget_221, "cam22" : self.ui.widget_222, "cam23" : self.ui.widget_223, 
                        "cam24" : self.ui.widget_224, "cam25" : self.ui.widget_225, "cam26" : self.ui.widget_226, "cam27" : self.ui.widget_227, 
                       

In [1]:
int("01")

1

In [1]:
3000*150

450000

In [2]:
100000000/450000

222.22222222222223

In [4]:
5400*3000/10000

1620.0

In [2]:
import numpy as np
a = np.array([0,0,0,0])

In [3]:
"Abcd" in a

C:\Users\user\AppData\Local\Temp/ipykernel_23640/489317283.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  "Abcd" in a


False